FROM ruby:3.3.12
RUN apt-get update -qq && apt-get install -y \
    build-essential libpq-dev libyaml-dev nodejs
WORKDIR /rails
COPY Gemfile Gemfile.lock* ./
RUN bundle install
COPY . .
CMD ["bin/rails", "server", "-b", "0.0.0.0"]